### ISSUE TITLE
Store offers in linked list?

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#24]
Should we be using a linked list to store the offers; since now a client need to iterate over all of them to create the orderbook (including all deleted ones).

**Comment by nmushegian** [comment]
No, we don't need to traverse it on chain (since we are specifically not creating a proper order book) so the overhead cost of maintaining the list is not worth it. A light client is not intended to be able to efficiently (ie not requiring a full chain log scan) find the best order in the long term. Sophisticated traders will maintain a full node with associated keeper tasks.

All that said, there's no reason it couldn't be a list type. You could eliminate `next_id` altogether (use `offers.length`) and adding an order is just `var id = offers.push(order)`

**Comment by ryepdx** [comment]
A mapping makes more sense given the way we're interacting with the data structure, IMO. It's unfortunate that it means clients will take longer and longer to get synced up as time goes on, of course.

Might be good to provide a hash of some kind in the contract that "light clients" can use to verify the order history they receive from more sophisticated traders.

**Comment by nmushegian** [comment]
We should release incrementally improved order types (including thing client friendly ones or other orthogonal features). Individual orders don't need to be future-proof at all.
