### ISSUE TITLE
Implement fallback function and reject any Ether sent to it

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#27]
Good practise to implement this:
https://solidity.readthedocs.org/en/latest/contracts.html#fallback-function

Why? Because people send Ether to random contracts and expect it to be accepted.. for example the Maker Distributor having 24 ETH sitting there forever.. https://etherscan.io/address/0xFd71d62A6dFE8B4E85A81f1d006E955f75AEc922

**Comment by nmushegian** [comment]
Yeah, and not just for rejecting mis-sent ether. Look at this insanity: https://github.com/nexusdev/dappsys/blob/0.3-dev/contracts/lang/fallback_tests.sol

I thought to solve this with a general-purpose `DSBase` type which would be `DSAuth` plus other opinionated defaults. I think the fallback should just throw: `function() { throw; }`

**Comment by ryepdx** [comment]
The `DSBase` solution sounds good to me. I'll go ahead and start on that in nexusdev/dappsys.

**Comment by ryepdx** [comment]
So, I spent a good chunk of today trying to build a DSBase solution, and I ended up making a more modest change to Dappsys due to the fact that fallback functions apparently cannot have their signatures changed by inheriting contracts. The PR can be found here: https://github.com/nexusdev/dappsys/pull/36

Feedback on this approach is welcomed.

**Comment by ryepdx** [comment]
Shimmed.
