### ISSUE TITLE
Pending transaction feedback for allowance & ETH deposit/withdrawals

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#43]
we’ll need some pending tx feedback for changing the allowance and ETH deposit/withdraws

**Comment by rainbeam** [comment]
Agreed. Some visual clue to let the user know that their button click actually did something. Relates a bit to #38.

Some ideas:

- timer showing time elapsed since last block
- button colour change on press, another colour on success
- list of currently queued actions (if user clicks several buttons within one block)
