### ISSUE TITLE
Determine order price / amount from total

### ISSUE THREAD

**Issue by rainbeam** [MakerDAO/maker-otc#45]
Currently have to specify price and amount to fill out an order - the total is determined from these. You can't specify the total first.

Instead, allow specification of any two of price / amount / total, from which the remaining one is determined.

See e.g. bitshares for working example.

**Comment by NTPape** [comment]
You can't specify total first, but you can specify price and then total, and the amount will be calculated.

In my PR #54 I actually disallowed total to be changed before price, because I find it unintuitive that you could change it, but it would then just be reset if you changed one of the other values.

In bitshares, setting total or amount if no price is set, will also reset the other two fields. For example setting amount and total will not calculate you the price there, either.

We're actually pretty close to bitshares already, the only difference being that you have to specify price and then total, while in bitshares you can also do total and then price. But apart from that, I think it's pretty much identical.

**Comment by nmushegian** [comment]
You can specify the total first if you know the inverse cost curve. It should be easier to think about once we straighten this out: https://github.com/MakerDAO/maker-otc/issues/5

**Comment by rainbeam** [comment]
@NTPape: total then price is what I'm meaning.

@nmushegian: I'm only meaning order make, not take, so don't need to know the cost curve.

**Comment by rainbeam** [comment]
I think this is intuitive because it lets you reason about orders in either token, e.g. 'I have 1000 ETH and want to buy MKR at 5 ETH / MKR' vs. 'I want 200 MKR at 5 ETH / MKR'.

**Comment by NTPape** [comment]
Both of these work already, you just have to enter the price before the total. With amount and price the order is even irrelevant.

Yes, I knew you meant total then price, but allowing that will introduce its own set of problems. Right now changing the price will recalculate the total. If we recalculated the amount instead, amount then price would stop working, etc.

Of course we could dynamically change which changes trigger a recalculation of which values (we would have to do something dynamic to make all the cases work that you request), but I would argue this would only make the whole thing even more unintuitive.

I find it reasonable to let the user enter his price first before anything else because it's the most important thing of a new order, maybe even disabling the total input before he does so while displaying a little helper text stating that the price needs to be set first.

**Comment by rainbeam** [comment]
Ok, let's close this with #108. Can re-open if there is sufficient user feedback.
