### ISSUE TITLE
EIP20 / non-MAR tokens

### ISSUE THREAD

**Issue by nmushegian** [MakerDAO/maker-otc#7]
An opportunity to consider a union type like:

```
struct token_desc {
     bool is_symbol;
     bytes20 symbol_or_address;
}

function extractToken(token_desc t) returns (address) {
    if( t.is_symbol ) {
        return _registry.getToken(bytes32(t.symbol_or_address));
    } else {
        return address(t.symbol_or_address);
}
```

A more future-proof alternative which efficiently uses 1 word (optimal use of mapping value space):

```
struct token_desc {
    bytes12 metadata;
    bytes20 address_or_symbol;
}
```

**Comment by nmushegian** [comment]
Possibly use of `metadata` includes short id's for a meta-registry of some kind

**Comment by ryepdx** [comment]
I really like the future-proof alternative.

**Comment by ryepdx** [comment]
I think there's probably more here that needs to be dug through. It kind of cuts against the grain of maker-user. Not sure this is something we can have ready soon.

**Comment by jorisbontje** [comment]
Comments on this by Vitalik on [Reddit]( https://www.reddit.com/r/ethtrader/comments/4gkc1h/simple_onchain_otc_market_alpha_release/d2j3rxn):
> Let people "submit" their own currency by specifying an address and a ticker symbol. For simplicity and safety, this should probably only stay in localstorage (or even not be saved at all); but this would let people trade DGX, DGD, eventually REP, "the DAO" shares, etc.

**Comment by nmushegian** [comment]
I propose we don't do MAR lookups at all, and do everything by address. The registry is over-engineering, if we're going to allow custom tokens at all then a UI-level "registry" gives the users the same kind of guarantees

**Comment by nmushegian** [comment]
It might make sense to put by-address stuff into MakerUser, so we can put our fail-on-throw there

**Comment by jorisbontje** [comment]
To summarize:

nikolai [8:54 PM] 
the only reason for on-chain symbol registries is that Maker wants to control "transitions" of tokens that are used in CDPs

jorisbontje [8:54 PM] 
I see various options being mentioned; simplest to me seems to replace `bytes32 sell_which_token` with address types consistently and handle everything else frontend wise

nikolai [8:54 PM] 
for short-running contracts, I think using addresses is fine 99% of the time
right.
that's why I suggest just using addresses everywhere for these type of apps

jorisbontje [8:56 PM] 
further we’ll use https://github.com/MakerDAO/maker-otc/blob/master/contracts/assertive.sol consistently (or wait for it to appear in maker-user as a wrapper) for all token transfer / transferFrom calls

nikolai [8:57 PM] 
you mean because there is no throw-on-fail if you use addresses. perhaps MakerUser should have a throw-on-fail version, which takes address instead of symbol?

`transfer(bob, 100, "DAI")` becomes `transfer(bob, 100, DAI_ADDR)`

jorisbontje [9:00 PM] 
we’d be calling the DSToken interface directly, rather than going through the https://github.com/MakerDAO/maker-user/blob/master/contracts/generic.sol interface
looks like we won’t need maker-user at all anymore

nikolai [9:05 PM] 
yep, and if all you need is `DSToken` then actually probably all you need is https://github.com/nexusdev/erc20

[9:05] 
`DSToken` has `updateAuthority` and other dappsys-related opinionations

[9:05] 
for example https://github.com/nexusdev/token-auction is a generic token app, not makeruser

**Comment by jorisbontje** [comment]
DGD token details: https://gist.github.com/tymat/caa79528615ad600f216e2e6f6b6e3c3

**Comment by jorisbontje** [comment]
Merged in `erc20` branch.
