### ISSUE TITLE
Explain LPC in math notation one-pager

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#71]
Request from @NTPape: please provide a one page explanation with proper math notation where you explain how you want the LPC to work (especially the cost calculation part, slope and error).

**Comment by nmushegian** [comment]
We can start with a simpler version, where one of the parameters is changed with a call to `reset` instead of varying over time.

To specify an LPC which sells ETH for dai, we owner defines a **dai price at ETH quantity** function, which tells you the instantaneous price of the last delta of ETH you'd be buying.

`priceAt(quantity) = slope * qantity + (feed_price * error)`

We also have a notion of `eth_sold`:

`buyCost(quantity) = integral_{eth_sold}^{quantity + eth_sold}   p(q) dq`

In this simple version, `eth_sold` is simply updated to be `quantity + eth_sold`, and is reset to 0 on `reset`.

The time-based component I want to add once a POC of this is working, is to have "eth_sold" decay back to 0 *so that the dai amount appears to be "refilling" at a constant rate* - this requires computing the inverse of the integral above. Actually, it's even worse, because this gives the market an explicit orientation, since one of the two assets is going to be the one that is stable (you always want to specify rate in terms of dai, regardless of which one you are selling).

**Comment by nmushegian** [comment]
@NTPape is this explanation clear?

**Comment by nmushegian** [comment]
https://ipfs.pics/QmdPyfaGTy6EuRo7BHN84pmiW3nsAu35Ffzrip5QgTRRXg

here I use `+ error` instead of `* error`, this is more accurate because `error` is like 0.05 whereas 1.05 should be called `deviation`

**Comment by nmushegian** [comment]
The integrand is also ambiguous in the picture - `p(q)dq` shouldn't be referencing `q` but a new integration variable

**Comment by NTPape** [comment]
The whole system only works as good as the price feed. As you can fill your own orders there's always a risk of price feed manipulation to get cheap tokens from the LPC.

If you want `error` to be `0.05` instead of `1.05` then you should use `* (1 + error)` instead of `+ error`, because otherwise the error would not be relative to the price anymore, unless of course you want it to be absolute.

Referring to the picture, the antiderivative of `p(q)` is slightly wrong, the second term should be `(f + e) * g`, or in case of my above suggestion to make it relative again `f * (1 + e) * g`.

Yes, the explanation is clearer now, thanks!

**Comment by jorisbontje** [comment]
@nmushegian can you update your diagrams / explanation with the comments from @NTPape ?
